<?php

// COPYRIGHT (c) Alec Barber 2012
// ALL UNAUTHORISED COPYING, MODIFICATION, EXPLOITATION FOR ANY FORM OF GAIN AND OTHER ACTIVITIES (EXCEPT USE AS A WEBPAGE - ie ACCESS OF vast-ridge-8542.herokuapp.com FROM A WEB BROWSER) ARE EXPRESSLY PROHIBITED WITHOUT THE EXPRESS PERMISSION OF THE COPYRIGHT HOLDER.
// THOSE GRANTED PERMISSION TO DO ANY OF THE ABOVE WITH THIS WORK CANNOT GIVE, SELL, BEQUEATH OR TRANSFER IN ANY WAY THE WHOLE OR ANY PART OF THAT PERMISSION TO OTHERS.

$uri=replace('#','&',$_SERVER['REQUEST_URI']);
$nURL=sprintf("Location: http://%s/%s",$_GET['ip'],$uri);
header($nURL,true,302);

?>
